# Generated by Django 3.2.8 on 2021-12-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedingEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=100)),
                ('time_given', models.TimeField()),
                ('feeding_choice', models.IntegerField()),
            ],
        ),
    ]
