# Generated by Django 3.2.8 on 2021-12-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0003_feedingentries_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingentries',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='FeedingDay',
        ),
    ]
