# Generated by Django 3.2.8 on 2021-12-12 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0004_auto_20211209_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingentries',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
