# Generated by Django 3.2.8 on 2021-12-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0006_auto_20211211_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreathingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=100)),
                ('time_given', models.TimeField()),
                ('breathing_choice', models.IntegerField()),
                ('day', models.IntegerField()),
                ('isoweek', models.IntegerField()),
            ],
        ),
    ]
