# Generated by Django 3.2.8 on 2021-12-12 18:15

from django.db import migrations, models
import interventions.models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0007_breathingentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breathingentry',
            name='time_given',
            field=models.TimeField(validators=[interventions.models.BreathingEntry.no_future]),
        ),
        migrations.AlterField(
            model_name='feedingentries',
            name='time_given',
            field=models.TimeField(validators=[interventions.models.FeedingEntries.no_future]),
        ),
    ]
