# Generated by Django 3.2.8 on 2021-11-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=200)),
                ('nurse', models.CharField(max_length=200)),
                ('med', models.CharField(max_length=200)),
                ('given', models.BooleanField(default=False)),
            ],
        ),
    ]
