# Generated by Django 3.2.8 on 2021-11-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marscheduled',
            options={'verbose_name_plural': 'Mar scheduled'},
        ),
    ]
