# Generated by Django 3.2.8 on 2021-11-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mar', '0002_alter_mar_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mar',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
