# Generated by Django 3.2.8 on 2021-11-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mar', '0002_alter_marscheduled_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marprn',
            options={'ordering': ['-mar_datetime']},
        ),
    ]
