# Generated by Django 3.2.8 on 2021-11-13 04:24

from django.db import migrations, models
import mar.models


class Migration(migrations.Migration):

    dependencies = [
        ('mar', '0003_alter_marprn_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marprn',
            name='mar_datetime',
            field=models.DateTimeField(validators=[mar.models.MarPrn.no_future]),
        ),
    ]
