# Generated by Django 3.2.8 on 2021-11-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('initials', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('initials', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Suction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('initials', models.CharField(max_length=200)),
            ],
        ),
    ]
