# Generated by Django 3.2.8 on 2021-10-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dose', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=200)),
                ('times', models.CharField(max_length=200)),
            ],
        ),
    ]
