# Generated by Django 3.2.8 on 2021-11-06 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrnMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dose', models.CharField(max_length=200)),
                ('indication', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dose', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=200)),
                ('times', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MarScheduled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given', models.BooleanField(default=False)),
                ('mar_date', models.DateField()),
                ('nurse', models.CharField(max_length=20)),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meds.scheduledmed')),
            ],
        ),
    ]
