# Generated by Django 3.2.8 on 2021-11-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marscheduled',
            name='time',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
