# Generated by Django 3.2.8 on 2021-11-09 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0002_marscheduled_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarPrn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mar_datetime', models.DateTimeField()),
                ('initial', models.CharField(max_length=20)),
                ('indication', models.CharField(max_length=200)),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meds.prnmed')),
            ],
        ),
    ]
