# Generated by Django 3.2.8 on 2021-11-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('size', models.CharField(choices=[('SMALL', 'small'), ('MED', 'medium'), ('LARGE', 'large')], max_length=20)),
                ('comment', models.CharField(max_length=200)),
                ('initial', models.CharField(max_length=20)),
            ],
        ),
    ]
