# Generated by Django 3.2.8 on 2021-11-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bm',
            name='size',
            field=models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], max_length=20),
        ),
    ]
