# Generated by Django 3.2.8 on 2021-11-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm', '0002_alter_bm_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bm',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
