# Generated by Django 3.2.8 on 2021-11-13 04:08

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm', '0003_alter_bm_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bm',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='bm',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator(datetime.date.today)]),
        ),
    ]
