# Generated by Django 3.2.8 on 2021-11-13 04:09

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm', '0004_auto_20211112_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bm',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator(datetime.datetime.now)]),
        ),
    ]
