# Generated by Django 3.2.8 on 2021-11-13 04:11

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm', '0005_alter_bm_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bm',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator(django.utils.timezone.now)]),
        ),
    ]
