# Generated by Django 3.2.8 on 2021-11-13 04:14

import bm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm', '0006_alter_bm_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bm',
            name='date',
            field=models.DateTimeField(validators=[bm.models.BM.no_future]),
        ),
    ]
